# Generated by Django 3.2.7 on 2021-09-07 08:09

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deathdtails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased',
            name='nationality',
            field=django_countries.fields.CountryField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
